[project]
name = "odoo"
version = "19.0"

# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration
# https://github.com/orhun/git-cliff/blob/main/examples/github-keepachangelog.toml

[tool.git-cliff.remote.github]
owner = "Dato-Veritas"
repo = "odoo"

[tool.git-cliff.changelog]
# A Tera template to be rendered as the changelog's header.
# See https://keats.github.io/tera/docs/#introduction
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}]
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | upper_first | trim }} \
            ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor %}\n
"""
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
footer = """
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
                    /compare/{{ release.previous.version }}..{{ release.version }}
        {% else -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
                    /tree/{{ release.version }}
        {% endif -%}
    {% else -%}
        [unreleased]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
            /compare/{{ release.previous.version }}..HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true

[tool.git-cliff.git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = false
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
  # Remove issue numbers.
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
# https://www.odoo.com/documentation/19.0/contributing/development/git_guidelines.html#tag-and-module-name
commit_parsers = [
    { message = "^\\[FIX\\]", group = "Bug Fixes" },
    { message = "^\\[IMP\\]", group = "Improvements" },
    { message = "^\\[ADD\\]", group = "New Features/Modules" },
    { message = "^\\[REF\\]", group = "Refactoring" },
    { message = "^\\[REM\\]", group = "Removals" },
    { message = "^\\[REV\\]", group = "Reverts" },
    { message = "^\\[MOV\\]", group = "Movements" },
    { message = "^\\[REL\\]", group = "Releases" },
    { message = "^\\[PERF\\]", group = "Performance" },
    { message = "^\\[CLN\\]", group = "Cleanup" },
    { message = "^\\[LINT\\]", group = "Linting" },
    { message = "^\\[I18N\\]", group = "Internationalization" },
    { message = "^\\[MERGE\\]", group = "Merges" },
    { message = "^\\[CLA\\]", skip = true },
    { message = ".*", group = "Other" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "newest"

# Sets the regex for matching git tags
tag_pattern = "^19\\.0\\.\\d{8}$"

# Regex for tags to completely skip
# This completely drops commits associated with the matched tags from the changelog.
skip_tags = ""
ignore_tags = ""

[tool.git-cliff.remote]
# This feature disables all external network calls, which is useful in restricted environments. 
offline = true